# .streamlit/config.toml

[client]
showSidebarNavigation = false

[theme]
primaryColor = "#E6B4A9"
backgroundColor = "#FDFBFA"
secondaryBackgroundColor = "#FBF6F1"
textColor = "#312B29"
font = "sans serif"
